# Generated by Django 5.1 on 2024-08-22 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adoption_date', models.DateTimeField(auto_now_add=True)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.adopter')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.helper')),
            ],
        ),
    ]
